name: ğŸš€ Deploy website on push to master branch

on: 
  push:
    branches: [ "main" ]
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
  schedule:
  - cron:  '0 8 * * *' #every day at 8 am

jobs:
  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    steps:

    - name: ğŸšš Get latest code
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: ğŸ”¨ Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'

    - name: ğŸ—ï¸ Build site
      run: hugo --minify

    - name: ğŸ“‚ FTP Upload
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: alifelivedfully.com
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        local-dir: public/
